server:
  port: 8081
spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.transaction.interceptor : trace
    org.springframework.orm.jpa.JpaTransactionManager : trace
